"""switch products and quantities to raw units instead of packets

Revision ID: 3a89fe6ec63a
Revises: dc3e3e5de02f
Create Date: 2026-07-24 00:01:49.372075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a89fe6ec63a'
down_revision = 'dc3e3e5de02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_logs', schema=None) as batch_op:
        batch_op.alter_column('quantity_produced',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bulk_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bulk_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('packet_size')
        batch_op.drop_column('packet_price')
        batch_op.create_check_constraint('ck_product_bulk_size_positive', 'bulk_size > 0')

    with op.batch_alter_table('route_trip_items', schema=None) as batch_op:
        batch_op.alter_column('qty_sent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('qty_returned',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('store_sales', schema=None) as batch_op:
        batch_op.alter_column('qty_sold',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('unit_price_snapshot',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_sales', schema=None) as batch_op:
        batch_op.alter_column('unit_price_snapshot',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('qty_sold',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('route_trip_items', schema=None) as batch_op:
        batch_op.alter_column('qty_returned',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('qty_sent',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('ck_product_bulk_size_positive', type_='check')
        batch_op.add_column(sa.Column('packet_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('packet_size', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('bulk_price')
        batch_op.drop_column('bulk_size')

    with op.batch_alter_table('production_logs', schema=None) as batch_op:
        batch_op.alter_column('quantity_produced',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
