"""add qty_damaged to route_trip_items

Revision ID: bf39e0f7038b
Revises: b3a52e78b906
Create Date: 2026-09-27 09:40:05.339247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf39e0f7038b'
down_revision = 'b3a52e78b906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_trip_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty_damaged', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_check_constraint('ck_trip_item_damaged_nonneg', 'qty_damaged >= 0')
        batch_op.create_check_constraint(
            'ck_trip_item_damaged_le_returned', 'qty_returned IS NULL OR qty_damaged <= qty_returned'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_trip_items', schema=None) as batch_op:
        batch_op.drop_constraint('ck_trip_item_damaged_le_returned', type_='check')
        batch_op.drop_constraint('ck_trip_item_damaged_nonneg', type_='check')
        batch_op.drop_column('qty_damaged')

    # ### end Alembic commands ###
