"""initial schema

Revision ID: dc3e3e5de02f
Revises: 
Create Date: 2026-07-23 00:11:07.734362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3e3e5de02f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('packet_size', sa.Integer(), nullable=False),
    sa.Column('packet_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_route_weekday_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('quantity_produced >= 0', name='ck_production_qty_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_logs_date'), ['date'], unique=False)

    op.create_table('route_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('loaded', 'in_progress', 'completed')", name='ck_route_trip_status'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'date', name='uq_route_trip_route_date')
    )
    with op.batch_alter_table('route_trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_trips_date'), ['date'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_trip_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_trip_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_sent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qty_returned', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('qty_returned IS NULL OR qty_returned <= qty_sent', name='ck_trip_item_returned_le_sent'),
    sa.CheckConstraint('qty_sent >= 0', name='ck_trip_item_qty_sent_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['route_trip_id'], ['route_trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_trip_id', 'product_id', name='uq_trip_item_product')
    )
    op.create_table('store_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_trip_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty_sold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_pending', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('voided', sa.Boolean(), nullable=False),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_store_sale_amount_nonneg'),
    sa.CheckConstraint('amount_collected >= 0', name='ck_store_sale_collected_nonneg'),
    sa.CheckConstraint('qty_sold >= 0', name='ck_store_sale_qty_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['route_trip_id'], ['route_trips.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_sales_date'), ['date'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('linked_store_sale_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=False),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("type IN ('sale-linked', 'standalone collection', 'adjustment')", name='ck_payment_type'),
    sa.ForeignKeyConstraint(['linked_store_sale_id'], ['store_sales.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linked_store_sale_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_date'))

    op.drop_table('payments')
    with op.batch_alter_table('store_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_sales_date'))

    op.drop_table('store_sales')
    op.drop_table('route_trip_items')
    op.drop_table('stores')
    with op.batch_alter_table('route_trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_trips_date'))

    op.drop_table('route_trips')
    with op.batch_alter_table('production_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_logs_date'))

    op.drop_table('production_logs')
    op.drop_table('routes')
    op.drop_table('products')
    # ### end Alembic commands ###
